name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Remplace par 'master' si le nom de ta branche principale est master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-step: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Dossier où se trouvent les fichiers de ton site (change si build React/Vue)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4